site_name: stove
site_description: Hot-reloader for HTTP servers.

docs_dir: docs
repo_url: https://github.com/athnomedical/stove
repo_name: athnomedical/stoveh

theme:
  name: material
  logo: res/icon-stove.jpg
  favicon: res/icon-stove.jpg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - search.highlight
  language: en
  palette:
    primary: red

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/athnomedical/stove

plugins:
  - search
  - mkdocstrings:
      default_handler: python
